
import { Button } from "@/components/ui/button";
import { ArrowDown, FileText } from "lucide-react";
import Link from "next/link";

export default function HeroSection() {
  return (
    <section id="home" className="min-h-[calc(100vh-4rem)] md:min-h-screen flex flex-col justify-center py-12 sm:py-16 md:py-20 text-left relative overflow-hidden">
      {/* Animated Background Elements */}
      <div className="hero-bg-animation-container"> {/* Removed -z-10, and background-color which is now on this element */}
        {/* Small Circles will be generated by ::before and ::after on this container via CSS */}
        <div className="bg-triangle triangle-1"></div>
        <div className="bg-triangle triangle-2"></div>
        <div className="bg-triangle triangle-3"></div>
        <div className="bg-orb orb-1"></div>
        <div className="bg-orb orb-2"></div>
        <div className="bg-orb orb-3"></div>
      </div>

      <div className="container mx-auto max-w-3xl relative z-10">
        <p className="text-lg text-primary mb-2 animate-fadeInUp" style={{ animationDelay: '0.1s' }}>
          Hello, I&apos;m
        </p>
        <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold text-foreground mb-4 animate-fadeInUp" style={{ animationDelay: '0.2s' }}>
          Kailas <span className="text-fire-gradient">Sachdev</span>.
        </h1>
        <h2 className="text-2xl sm:text-3xl md:text-4xl font-semibold text-muted-foreground mb-8 animate-fadeInUp" style={{ animationDelay: '0.3s' }}>
          I build things: from deep learning models to full-stack web experiences.
        </h2>
        <p className="text-base sm:text-lg text-muted-foreground mb-10 max-w-xl animate-fadeInUp" style={{ animationDelay: '0.4s' }}>
          I&apos;m a software engineer specializing in creating robust and scalable applications.
          Driven by curiosity and a passion for innovation and community impact.
        </p>
        <div className="space-x-0 sm:space-x-4 space-y-4 sm:space-y-0 flex flex-col sm:flex-row items-start animate-fadeInUp" style={{ animationDelay: '0.5s' }}>
          <Button size="lg" asChild className="bg-primary hover:bg-primary/90 text-primary-foreground w-full sm:w-auto">
            <Link href="#contact">
              Get In Touch
            </Link>
          </Button>
          {/* <Button size="lg" variant="outline" asChild className="border-primary text-primary hover:bg-primary/10 w-full sm:w-auto">
            <Link href="/resume.pdf" target="_blank" rel="noopener noreferrer">
              View My Resume <FileText className="ml-2 h-5 w-5" />
            </Link>
          </Button> */}
        </div>
      </div>
    </section>
  );
}
